### ISSUE TITLE
Error when flipping a card

### ISSUE THREAD

**Issue by agrtga** [spacemandev-git/fvtt-card-support#18] opened 2020-08-26 00:35 UTC
I have a hand of six cards. The last two will flip as expected when I choose Flip Card. However, the first four fail to flip and a generic error "What you doing m8? Stop breaking Spaceman's code that Norc stole..." is displayed briefly.

**Comment by Norc** [comment] 2020-08-26 10:41
Hey agrtga...

1. Can you try uninstalling and reinstalling the module to unsure you are on the latest version?
2. Press the "Discard Entire Hand" button in the vertical Card Hotbar to the left of the cards and resetting the deck. Can you still reproduce this issue?
3. If you still can, can you reproduce it in a clean test world?

Thanks, I can't reproduce this issue on my end. If you can, I'll try again and/or might need to connect to your world or discuss on discord further (Norc#5108).

Thanks for using the module, and good luck!

**Comment by agrtga** [comment] 2020-08-26 15:10
I was able to fix the problem by dragging the card onto the scene, and then taking it back. After that it would flip.

**Comment by Norc** [comment] 2020-08-26 15:33
Awesome. I'm going to close this for now then.  

I'm uncertain what the root cause of the issue was though. If you do see any other oddities please let us know so we can track down whatever caused this... hopefully it was a one-off related to a previous version somehow.

Thank you for the report and even more for the follow-up!

**Closed by Norc** 2020-08-26 15:33 UTC
